const Constants = {
    SET_MOVIE: 'SET_MOVE',
    SET_REVIEW: 'SET_REVIEW',
    FETCH_MOVIE: 'FETCH_MOVIE',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_MOVIES: 'FETCH_MOVIES',
    USER_LOGGEDIN: 'USER_LOGGEDIN',
}

export default Constants;